---
- name: redhat | Adding EPEL Repo
  package:
    name: epel-release
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Installing Pre-Reqs
  package:
    name: "{{ kea_dhcp_pre_reqs }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: redhat | Adding Kea DHCP Repo Key
  rpm_key:
    key: "{{ kea_dhcp_repo_key }}"
    state: present
  become: true

- name: redhat | Kea DHCP
  block:
    - name: redhat | Adding Kea DHCP Repo
      yum_repository:
        name: "isc-kea-{{ kea_dhcp_version|replace('.', '-') }}"
        description: "isc-kea-{{ kea_dhcp_version|replace('.', '-') }}"
        baseurl: >-
          "%s/rpm/el/%s/$basearch" |
          format(
            kea_dhcp_base_url,
            hostvars[inventory_hostname]ansible_distribution_major_version
          )
        gpgcheck: true
        enabled: true
        gpgkey: "{{ kea_dhcp_repo_key }}"
        state: present
      become: true

    - name: redhat | Adding Kea DHCP Repo (noarch)
      yum_repository:
        name: "isc-kea-{{ kea_dhcp_version|replace('.', '-') }}-noarch"
        description: "isc-kea-{{ kea_dhcp_version|replace('.', '-') }}-noarch"
        baseurl: >-
          "%s/rpm/el/%s/noarch" |
          format(
            kea_dhcp_base_url,
            hostvars[inventory_hostname]ansible_distribution_major_version
          )
        gpgcheck: true
        enabled: true
        gpgkey: "{{ kea_dhcp_repo_key }}"
        state: present
      become: true

    - name: redhat | Adding Kea DHCP Repo (source)
      yum_repository:
        name: "isc-kea-{{ kea_dhcp_version|replace('.', '-') }}-source"
        description: "isc-kea-{{ kea_dhcp_version|replace('.', '-') }}-source"
        baseurl: >-
          "%s/rpm/el/%s/SRPMS" |
          format(
            kea_dhcp_base_url,
            hostvars[inventory_hostname]ansible_distribution_major_version
          )
        gpgcheck: true
        enabled: true
        gpgkey: "{{ kea_dhcp_repo_key }}"
        state: present
      become: true

- name: redhat | Installing Kea DHCP Packages
  package:
    name: "{{ kea_dhcp_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
