---
- name: set_facts | Setting Debian Pre-Reqs
  set_fact:
    kea_dhcp_pre_reqs:
      - apt-transport-https
      - debian-archive-keyring
      - debian-keyring
  when:
    - ansible_distribution == "Debian"

- name: set_facts | Setting Debian Pre-Reqs
  set_fact:
    kea_dhcp_pre_reqs:
      - apt-transport-https
  when:
    - ansible_distribution == "Ubuntu"

- name: set_facts | Setting RedHat Pre-Reqs
  set_fact:
    kea_dhcp_pre_reqs:
      - yum-utils
  when:
    - ansible_os_family == "RedHat"

- name: set_facts | Setting Repo Base Path
  set_fact:
    kea_dhcp_base_url: "{{ kea_dhcp_repo_prefix }}/kea-{{ kea_dhcp_version|replace('.', '-') }}"

- name: set_facts | Setting GPG Key URL
  set_fact:
    kea_dhcp_repo_key: >-
      {{
        "%s/cfg/gpg/gpg.%s.key" |
        format(kea_dhcp_base_url, kea_dhcp_key_fingerprint[kea_dhcp_version])
      }}

- name: set_facts | Setting Repo Info (Debian)
  set_fact:
    kea_dhcp_repo: >-
      deb
      {{ kea_dhcp_base_url }}/deb/{{ ansible_distribution|lower }}
      {{ ansible_distribution_release|lower }}
      main
  when:
    - ansible_os_family == "Debian"

- name: set_facts | Setting Kea Packages (Debian)
  set_fact:
    kea_dhcp_packages:
      - isc-kea-admin
      - isc-kea-dhcp-ddns-server
      - isc-kea-dhcp4-server
      - isc-kea-dhcp6-server
  when:
    - ansible_os_family == "Debian"

- name: set_facts | Setting Kea Packages (Ubuntu)
  set_fact:
    kea_dhcp_packages:
      - isc-kea-admin
      - isc-kea-dhcp-ddns-server
      - isc-kea-dhcp4-server
      - isc-kea-dhcp6-server
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('18.04', '>=')

- name: set_facts | Setting Kea Packages (RedHat)
  set_fact:
    kea_dhcp_packages:
      - isc-kea
  when:
    - ansible_os_family == "RedHat"

- name: set_facts | Setting Services Facts (Debian)
  set_fact:
    kea_dhcp_services:
      - name: isc-kea-dhcp-ddns-server
        enabled: "{{ kea_dhcp_service_state['ddns']|bool }}"
      - name: isc-kea-dhcp4-server
        enabled: "{{ kea_dhcp_service_state['ipv4']|bool }}"
      - name: isc-kea-dhcp6-server
        enabled: "{{ kea_dhcp_service_state['ipv6']|bool }}"
  when:
    - ansible_os_family == "Debian"

- name: set_facts | Setting Services Facts (RedHat)
  set_fact:
    kea_dhcp_services:
      - name: kea-dhcp-ddns
        enabled: "{{ kea_dhcp_service_state['ddns']|bool }}"
      - name: kea-dhcp4
        enabled: "{{ kea_dhcp_service_state['ipv4']|bool }}"
      - name: kea-dhcp6
        enabled: "{{ kea_dhcp_service_state['ipv6']|bool }}"
  when: ansible_os_family == "RedHat"
